PLMVC/Controllers/AseguradoraController.cs
using BL;
using ML;
using PLMVC.AseguradoraReference;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PLMVC.Controllers
{
    public class AseguradoraController : Controller
    {
        // GET: Aseguradora
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = new ML.Result();
            ML.Aseguradora aseguradora = new ML.Aseguradora();
            //ML.Result result = BL.Aseguradora.GetAllEF();
            AseguradoraReference.AseguradoraServiceClient aseguradoraClient = new AseguradoraReference.AseguradoraServiceClient();
            result = aseguradoraClient.GetAllEF();

            if (result.Correct)
            {
                aseguradora.Aseguradoras = result.Objects;
                return View(aseguradora);
            }
            else
            {
                return View(aseguradora);
            }
        }
        [HttpGet]
        public ActionResult Form(int? IdAseguradora)

        {

            ML.Result resultUsuarios = BL.Usuarios.GetAll();

            ML.Aseguradora aseguradora = new ML.Aseguradora();
            aseguradora.usuario = new ML.Usuario();


            if (resultUsuarios.Correct)
            {

                aseguradora.usuario.Usuarios = resultUsuarios.Objects;
            }
            if (IdAseguradora == null)
            {
                //add //formulario vacio
                return View(aseguradora);
            }
            else
            {
                //getById
                //ML.Result result = BL.Aseguradora.GetByIdEF(IdAseguradora.Value); //2
                ML.Result result = new ML.Result();
                AseguradoraReference.AseguradoraServiceClient aseguradoraClient = new AseguradoraReference.AseguradoraServiceClient();
                result = aseguradoraClient.GetByIdEF(IdAseguradora.Value);

                if (result.Correct)
                {

                    aseguradora = (ML.Aseguradora)result.Object;//unboxing
                    aseguradora.usuario.Usuarios = resultUsuarios.Objects;
                    //update
                    return View(aseguradora);
                }
                else
                {
                    ViewBag.Message = "Ocurrio al consultar la información de la aseguradora";
                    return View("Modal");
                }
            }
        }



        [HttpPost] //Hacer el registro
        public ActionResult Form(ML.Aseguradora aseguradora)
        {
            ML.Result result = new ML.Result();

            if (aseguradora.IdAseguradora != null)
            {

                //UPDATE
                AseguradoraReference.AseguradoraServiceClient aseguradoraClient = new AseguradoraReference.AseguradoraServiceClient();
                result = aseguradoraClient.UpdateEF(aseguradora);
                //result = BL.Aseguradora.UpdateEF(aseguradora);
                ViewBag.Message = "Se ha modificado el registro";
            }
            else
            {
                //Add
                AseguradoraReference.AseguradoraServiceClient aseguradoraClient = new AseguradoraReference.AseguradoraServiceClient();
                result = aseguradoraClient.AddEF(aseguradora);
                //result = BL.Aseguradora.AddEF(aseguradora);
                ViewBag.Message = "Se ha agregado el registro";
            }
            if (result.Correct)
            {
                return PartialView("Modal");
            }
            else
            {
                return PartialView("Modal");
            }
        }

        public ActionResult Delete(int IdAseguradora)
        {
            //ML.Result result = BL.Aseguradora.DeleteEF(IdAseguradora);
            ML.Result result = new ML.Result();

            AseguradoraReference.AseguradoraServiceClient aseguradoraClient = new AseguradoraReference.AseguradoraServiceClient();
            result = aseguradoraClient.DeleteEF(IdAseguradora);

            if (result.Correct)
            {
                ViewBag.Message = "Se ha eliminado el registro";
                return PartialView("Modal");
            }
            else
            {
                ViewBag.Message = "No se ha podido eliminar el registro seleccionado" + result.ErrorMessage;
                return PartialView("Modal");
            }
        }



    }
}

PLMVC/Views/Aseguradora/Form.cshtml
@model ML.Aseguradora
@{
    ViewBag.Title = "Form";
   ;
}

<h2>Formulario</h2>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Aseguradora</h2>
            <h5>Ingrese los datos de la aseguradora:</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <hr />
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Aseguradora", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.IdAseguradora, new { @class = "hidden" })
                            @Html.TextBoxFor(model => model.IdAseguradora, new { @class = "hidden form-control", autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.IdAseguradora)
                            @*hidden*@
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Nombre)
                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })
                            @Html.ValidationMessageFor(model => model.Nombre, null, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.FechaCreacion)
                            @Html.TextBoxFor(model => model.FechaCreacion, new { @class = "form-control", @id = "txtFechaCreacion" })
                            @Html.ValidationMessageFor(model => model.FechaCreacion, null, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.FechaModificacion)
                            @Html.TextBoxFor(model => model.FechaModificacion, new { @class = "form-control", @id = "txtFechaModificacion" })
                            @Html.ValidationMessageFor(model => model.FechaModificacion, null, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.usuario)
                            @Html.DropDownListFor(model => model.usuario.IdUsuario, new SelectList(Model.usuario.Usuarios, "IdUsuario", "NombreCompleto"), "Selecciona una opción", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.usuario.IdUsuario, null, new { @class = "text-danger" })
                        </div>
                        @*<div class="col-md-6">
                @Html.LabelFor(model => model.Usuario.IdUsuario)
                @Html.TextBoxFor(model => model.Usuario.IdUsuario, "{0:#.#}", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Usuario.IdUsuario)
            </div>*@
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Aseguradora", htmlAttributes: new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>


            }


        </div>
    </div>
</div>

PLMVC/Views/Aseguradora/GetAll.cshtml
@model ML.Aseguradora

@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="=col-md-12">
            <h2>Aseguradoras</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <h5>Seleccione Agregar para registrar una aseguradora</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1 ">
            @Html.ActionLink("Agregar", "Form", "Aseguradora", htmlAttributes: new { @class = "btn btn-success" })
        </div>
        <br> <br />
    </div>
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-responsive">
                <thead class="thead-dark">
                    <tr>
                        <td>Editar</td>
                        <td class="hidden">IdAseguradora</td>
                        <td>Nombre</td>
                        <td>Fecha de creación </td>
                        <td>Fecha de modificación</td>
                        <td>ID Usuario</td>
                        <td>User Name</td>
                        <td>Nombre</td>
                        <td>Apellido Paterno</td>
                        <td>Apellido Materno</td>

                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.Aseguradora aseguradora in Model.Aseguradoras)
                    {
                        <tr>
                            <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Aseguradora", new { IdAseguradora = aseguradora.IdAseguradora })"></a></td>

                            <td class="hidden">@aseguradora.IdAseguradora</td>
                            <td>@aseguradora.Nombre</td>
                            <td>@aseguradora.FechaCreacion</td>
                            <td>@aseguradora.FechaModificacion</td>
                            <td>@aseguradora.usuario.IdUsuario</td>
                            <td>@aseguradora.usuario.UserName</td>
                            <td>@aseguradora.usuario.Nombre</td>
                            <td>@aseguradora.usuario.ApellidoPaterno</td>
                            <td>@aseguradora.usuario.ApellidoMaterno</td>
                            <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-erase" href="@Url.Action("Delete", "Aseguradora", new { IdAseguradora = aseguradora.IdAseguradora })" onclick="return confirm('¿Estas seguro que deseas eliminar este registro?');"></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

PLMVC/Views/Aseguradora/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" name="eliminar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@
                @Html.ActionLink("Vale", "GetAll", "Aseguradora", htmlAttributes: new { @class = "btn btn-danger" })
                
            </div>
        </div>
    </div>
</div>

<script>
    $('#Modal').modal();
</script>